### ISSUE TITLE
Mutation information

### ISSUE THREAD

**Issue by santoshe1** [cov-lineages/scorpio#18]
Hello Scorpio Team,

Thank you for the such a great tool. I would like to know if we could get the information of which are the variations/mutations in addition to the count of ALT, REF or AMG variant counts from the scorpio results?

**Comment by rmcolq** [comment]
At the moment, no. Although there is the option to run `scorpio haplotype -i <alignment> -c <constellation json file>` and this will output a string for every sequence in the alignment which is essentially a concatenation of the calls for each mutation listed in order (puts `-` for reference by default `X` for missing/ambiguous/other, number of amino acid positions deleted and ? if insertion in definition as currently not supported)

**Comment by santoshe1** [comment]
Thank you @rmcolq for the information :)
