### ISSUE TITLE
Scorpio version reporting 0.3.5 incorrectly (?)

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/scorpio#21]
Updating pangolin reports that scorpio is being updated to 0.3.6, but scorpio -v still reports 0.3.5 after update.

https://github.com/cov-lineages/scorpio/blob/main/scorpio/__init__.py has 0.3.5 listed as the current version.

It is unclear if the current version in 0.3.5 or 0.3.6 and how to determine which version is installed locally.

**Comment by rmcolq** [comment]
Thank you - looks like the PR was not merged before the release. I've re-released it as v0.3.7 to fix
