### ISSUE TITLE
For `haplotype` command only use one directory of constellation files.

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/scorpio#25]
The `./constellation/data/` directory has a a miscellaneous bunch of constellation files. It would be better if Scorpio defaulted to only using files in `./constellation/definitions/` by default.

**Comment by rmcolq** [comment]
Constellations dev branch now has only the reference JSON in data, and the remainder in misc, which is not included automatically as per discussion.

**Comment by rmcolq** [comment]
Constellations dev branch now merged in - change effectively resolves this issue
