### ISSUE TITLE
scorpio overriding AY.4.2 to B.1.617.2 on very few Ns

### ISSUE THREAD

**Issue by mcroxen** [cov-lineages/scorpio#32]
Example: EPI_ISL_5076925

`EPI_ISL_5076925,AY.4.2,0.0,0.9996771068776235,Delta (AY.4.2-like),0.960800,0.000000,PLEARN-v1.2.86,3.1.15,2021-10-13,v1.2.86,passed_qc,scorpio call: Alt alleles 49; Ref alleles 0; Amb alleles 2; Oth alleles 0`

Note this genome has only 1 ambiguous base (Y:14120) and no Ns, so the Amb alleles 2 is unusual

Further, if we mutate positions as part of cAY.4.json (e.g., 13,322 and 28270-28,271), then pangolin will return B.1.617.2 as the lineage

`11332N|28270N|28271N,B.1.617.2,0.0,0.9990306946688207,Delta (B.1.617.2-like),1.000000,0.000000,PLEARN-v1.2.86,3.1.15,2021-10-13,v1.2.86,passed_qc,scorpio call: Alt alleles 13; Ref alleles 0; Amb alleles 0; Oth alleles 0; scorpio replaced lineage assignment AY.4.2`

Just to show that the correct mutations were introduced (nextclade output)

`seqName,deletions,missing,nonACGTN`
`EPI_ISL_5076925,"22029-22034,28248-28253,28271",,Y:14120`
`11332N|28270N|28271N,"22029-22034,28248-28253","11332,28270-28271",Y:14120`

**Comment by rmcolq** [comment]
Whilst it is still possible that we are getting more ambiguous calls than expected with scorpio, all examples I've looked at where this was causing a problem I think are now resolved. I'm going to close this issue but if an example is found again where there is still a problem, please do reopen
