### ISSUE TITLE
 CDS orf1a at position 741 is L, but reference sequence has F

### ISSUE THREAD

**Issue by tseemann** [cov-lineages/scorpio#8]
```
% scorpio -v
scorpio 0.2

% scorpio classify -i in.fasta 

couldn't parse the following string: s:417
couldn't parse the following string: s:445couldn't parse the following string: s:446
<snip>
 CDS orf1a at position 741 is L, but reference sequence has F
Looking in
<snip>
Found reference /home/tseemann/.conda/envs/pangolin/lib/python3.8/site-packages/constellations/data/SARS-CoV-2.json
Found constellations:
/home/tseemann/.conda/envs/pangolin/lib/python3.8/site-packages/constellations/data/3-VOCs.json
No rules provided to classify mutations

Parsing constellation JSON file /home/tseemann/.conda/envs/pangolin/lib/python3.8/site-packages/constellations/definitions/cA.23.1+E484K.json
variants file says reference amino acid in CDS orf1a at position 741 is L, but reference sequence has F
```

**Comment by tseemann** [comment]
Maybe it needs ALIGNED sequences as input?

if so, can it still detect INSERTIONS? or do you `mafft --keeplength`?

**Comment by tseemann** [comment]
This is happening within 3.0.3 pangiolin:

```        scorpio classify         -i /tmp/tseemann/tmp6di3r_8w/sequences.aln.fasta         -o /tmp/tseemann/tmp6di3r_8w/VOC_report.scorpio.csv         -t 1         --long &> /tmp/tseemann/tmp6di3r_8w/logs/scorpio.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time```

**Comment by aineniamh** [comment]
Hi @tseemann, there were initially some issues with the definitions in constellations, but I think that's been resolved now. Does a full environment update fix your issue? 
https://cov-lineages.org/pangolin_docs/updating.html

**Comment by rmcolq** [comment]
I'm going to tag the tips of constellations and scorpio so it's clear. Also push one more commit so that it's clear which of those stdout messages are just warnings. Only the last one is an error, and the tip of master on both commits should fix.

**Comment by rmcolq** [comment]
Hi @tseemann, I've done some cleaning up to those warnings, and added release tags to the working tips of both scorpio and constellations (constellations version v0.0.2 and scorpio version v0.3)

**Comment by tseemann** [comment]
Thanks @rmcolq - we think it was `--update` from 3.0.2 to 3.0.3 that broke it all.

Doing a fresh conda / git / pip setup resolved it.
